name: Main CI

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Check lint status
        run: npm run lint

      - name: Check test status
        run: npm run test

      - name: Check build status
        run: npm run build
